version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - ./.env.db
    networks:
      - djangonetwork
    restart: on-failure
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    volumes:
      - .:/usr/src/polls_app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
    restart: on-failure
volumes:
  postgres_data:

networks:
    djangonetwork:
        driver: bridge
